apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: foos.example.com # <names.plural>.<group>
spec:
  group: example.com
  names:
    kind: Foo
    plural: foos
  scope: Namespaced # `Cluster` and `Namespaced`
  versions:
    - name: v1alpha1
      served: true # served via REST APIs
      storage: true # There must be exactly one version with storage=true. StorageVersion
      additionalPrinterColumns:
        - name: Test String
          jsonPath: .testString
          type: string
        - name: Test Num
          jsonPath: .testNum
          type: integer
      schema:
        openAPIV3Schema:
          type: object
          properties:
            testString:
              type: string
            testNum:
              type: integer
